export const theme = {
  'text-basic-color': '#000',
  'text-alternate-color': '#00B0C8',
  'text-control-color': '#FFF',
  'text-hint-color': '#ADADAD',
  'text-info-color': '#DFDFDF',
  'text-warning-color': '#EFD4A1',
  'text-success-color': '#4AA68A',
  'text-danger-color': '#FF6E83',
  'color-primary-default': '#4AA68A',
  'color-basic-default': '#E5E5E5',
  'color-primary-100': '#FF6E83',
  'color-primary-200': '#EFD4A1',
  'color-primary-active': '#9DCEBF',
  'color-primary-focus': '#9DCEBF',
  'color-primary-hover': '#9DCEBF',
  'background-basic-color-1': '#FFF',
  'background-basic-color-2': '#EFEFEF',
  'background-basic-color-3': '#F6F6F6',
  'color-primary-disabled': '#EAEAEA',
  'color-primary-disabled-2': '#DDDDDD',
  'primary-control-color': '#121212',
};
